import { StyleSheet } from "react-native";

export const palette = {
  bgBase: "#090D13",
  bgSurface: "#121820",
  bgSubtle: "#1B222D",
  bgCard: "#161D27",
  border: "#283344",
  borderActive: "#3E4C63",
  textPrimary: "#F0F6FC",
  textSecondary: "#8B949E",
  textMuted: "#656D76",
  accent: "#58A6FF",
  accentHover: "#79C0FF",
  success: "#2EA043",
  successBg: "rgba(46, 160, 67, 0.15)",
  danger: "#F85149",
  dangerBg: "rgba(248, 81, 73, 0.15)",
  warning: "#D29922",
  warningBg: "rgba(210, 153, 34, 0.15)",
  info: "#388BFD",
  infoBg: "rgba(56, 139, 253, 0.15)",
  purple: "#BC8CFF",
  purpleBg: "rgba(188, 140, 255, 0.15)",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: palette.bgBase,
  },
  header: {
    padding: 16,
    backgroundColor: palette.bgSurface,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  titleCluster: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  titleText: {
    fontSize: 16,
    fontWeight: "700",
    color: palette.textPrimary,
    letterSpacing: -0.2,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  badgeRunning: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: palette.successBg,
  },
  badgeCompleted: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: palette.infoBg,
  },
  badgeIdle: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: palette.bgSubtle,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.textSecondary,
  },
  badgeTextRunning: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.success,
  },
  badgeTextCompleted: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.info,
  },
  badgeP0: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: palette.dangerBg,
  },
  badgeP1: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: palette.warningBg,
  },
  badgeP2: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: palette.infoBg,
  },
  badgeP3: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: palette.bgSubtle,
  },
  badgeTextP0: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.danger,
  },
  badgeTextP1: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.warning,
  },
  badgeTextP2: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.info,
  },
  badgeTextP3: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.textSecondary,
  },
  hopsLabel: {
    fontSize: 12,
    color: palette.textMuted,
  },
  activeUrlLabel: {
    fontSize: 11,
    color: palette.textSecondary,
    flex: 1,
    marginRight: 12,
  },
  progressBarTrack: {
    height: 6,
    backgroundColor: palette.bgSubtle,
    borderRadius: 3,
    overflow: "hidden",
    marginVertical: 8,
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: palette.accent,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.bgSubtle,
  },
  statPillSelected: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: palette.accent,
    backgroundColor: palette.accent,
  },
  statPillP0: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: palette.dangerBg,
  },
  statPillP1: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: palette.warningBg,
  },
  statPillP2: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: palette.infoBg,
  },
  statPillText: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.textSecondary,
  },
  statPillTextSelected: {
    fontSize: 11,
    fontWeight: "600",
    color: "#0D1117",
  },
  statPillTextP0: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.danger,
  },
  statPillTextP1: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.warning,
  },
  statPillTextP2: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.info,
  },
  controlsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  buttonPrimary: {
    backgroundColor: palette.accent,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    alignItems: "center",
  },
  buttonPrimaryText: {
    color: "#0D1117",
    fontWeight: "600",
    fontSize: 12,
  },
  buttonSecondary: {
    backgroundColor: palette.bgSubtle,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: "center",
  },
  buttonSecondaryText: {
    color: palette.textPrimary,
    fontWeight: "500",
    fontSize: 12,
  },
  buttonDanger: {
    backgroundColor: palette.dangerBg,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: palette.danger,
    alignItems: "center",
  },
  buttonDangerText: {
    color: palette.danger,
    fontWeight: "600",
    fontSize: 12,
  },
  listContent: {
    padding: 16,
    gap: 12,
  },
  emptyBox: {
    padding: 40,
    alignItems: "center",
  },
  emptyText: {
    color: palette.textMuted,
    fontSize: 13,
  },
  card: {
    backgroundColor: palette.bgCard,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    padding: 14,
    gap: 8,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: palette.textPrimary,
    flex: 1,
    marginRight: 8,
  },
  occurrenceText: {
    fontSize: 11,
    color: palette.textMuted,
  },
  sourceHintText: {
    fontSize: 11,
    color: palette.accent,
  },
  suggestedFixText: {
    fontSize: 12,
    color: palette.textSecondary,
  },
  codeBox: {
    backgroundColor: palette.bgBase,
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: palette.border,
  },
  codeText: {
    fontFamily: "monospace",
    fontSize: 11,
    color: palette.textSecondary,
  },
  cardActionsRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  actionWorkingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  actionWorkingText: {
    fontSize: 12,
    color: palette.accent,
  },
  resolvedBadge: {
    backgroundColor: palette.successBg,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  resolvedBadgeText: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.success,
  },
  lanesRow: {
    flexDirection: "row",
    gap: 10,
    padding: 12,
    backgroundColor: palette.bgSurface,
    borderTopWidth: 1,
    borderTopColor: palette.border,
  },
  laneCard: {
    flex: 1,
    backgroundColor: palette.bgCard,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 10,
    gap: 6,
  },
  laneHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  laneTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: palette.textPrimary,
  },
  laneWorkingText: {
    fontSize: 11,
    color: palette.accent,
  },
  laneIdleText: {
    fontSize: 11,
    color: palette.textMuted,
  },
  lanePrText: {
    fontSize: 11,
    color: palette.success,
  },
  laneFailedText: {
    fontSize: 11,
    color: palette.danger,
  },
  laneBranchText: {
    fontSize: 10,
    color: palette.textMuted,
  },
  rowBetweenCenter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  filterPillRow: {
    flexDirection: "row",
    gap: 6,
  },
});
