import type { PluginWorkflowPreset } from "@getpaseo/plugin/server";
import type { GiteaWorkflowPolicy } from "../../shared/types.js";

interface StepDefinition {
  id: string;
  type: string;
  dependsOn?: string[];
  input?: Record<string, unknown>;
  timeoutMs: number;
  retries: number;
  concurrency: number;
  approval: "required" | "automatic";
}

export function buildGiteaWorkflowDefinition(strategy: GiteaWorkflowPolicy = "full_superpowers") {
  const steps: StepDefinition[] = [
    {
      id: "fetch-issue",
      type: "gitea.fetch_issue",
      timeoutMs: 30_000,
      retries: 2,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "claim-issue",
      type: "gitea.claim_issue",
      dependsOn: ["fetch-issue"],
      timeoutMs: 30_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "worktree-create",
      type: "worktree.create",
      dependsOn: ["claim-issue"],
      timeoutMs: 60_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
  ];

  if (strategy === "full_superpowers") {
    steps.push(
      {
        id: "brainstorm-agent",
        type: "gitea.agent_execute",
        dependsOn: ["worktree-create"],
        input: { phase: "brainstorm" },
        timeoutMs: 30 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "automatic",
      },
      {
        id: "design-approval",
        type: "approval.wait",
        dependsOn: ["brainstorm-agent"],
        input: { reason: "Design proposal requires human approval" },
        timeoutMs: 60 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "required",
      },
      {
        id: "spec-agent",
        type: "gitea.agent_execute",
        dependsOn: ["design-approval"],
        input: { phase: "spec" },
        timeoutMs: 30 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "automatic",
      },
      {
        id: "spec-approval",
        type: "approval.wait",
        dependsOn: ["spec-agent"],
        input: { reason: "Design spec requires human approval" },
        timeoutMs: 60 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "required",
      },
      {
        id: "plan-agent",
        type: "gitea.agent_execute",
        dependsOn: ["spec-approval"],
        input: { phase: "plan" },
        timeoutMs: 30 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "automatic",
      },
      {
        id: "plan-approval",
        type: "approval.wait",
        dependsOn: ["plan-agent"],
        input: { reason: "Implementation plan requires human approval" },
        timeoutMs: 60 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "required",
      },
      {
        id: "implement-agent",
        type: "gitea.agent_execute",
        dependsOn: ["plan-approval"],
        input: { phase: "implement" },
        timeoutMs: 60 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "automatic",
      },
    );
  } else if (strategy === "issue_preapproved") {
    steps.push(
      {
        id: "plan-agent",
        type: "gitea.agent_execute",
        dependsOn: ["worktree-create"],
        input: { phase: "plan" },
        timeoutMs: 30 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "automatic",
      },
      {
        id: "plan-approval",
        type: "approval.wait",
        dependsOn: ["plan-agent"],
        input: { reason: "Implementation plan requires human approval" },
        timeoutMs: 60 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "required",
      },
      {
        id: "implement-agent",
        type: "gitea.agent_execute",
        dependsOn: ["plan-approval"],
        input: { phase: "implement" },
        timeoutMs: 60 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "automatic",
      },
    );
  } else {
    // unattended strategy: proceed without intermediate approval pauses
    steps.push(
      {
        id: "plan-agent",
        type: "gitea.agent_execute",
        dependsOn: ["worktree-create"],
        input: { phase: "plan" },
        timeoutMs: 30 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "automatic",
      },
      {
        id: "implement-agent",
        type: "gitea.agent_execute",
        dependsOn: ["plan-agent"],
        input: { phase: "implement" },
        timeoutMs: 60 * 60 * 1000,
        retries: 0,
        concurrency: 1,
        approval: "automatic",
      },
    );
  }

  // Final verification, independent review, manifest gate and delivery
  steps.push(
    {
      id: "verify-command",
      type: "verify.command",
      dependsOn: ["implement-agent"],
      input: { verificationProfile: "unit-test" },
      timeoutMs: 15 * 60 * 1000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "independent-review",
      type: "gitea.agent_execute",
      dependsOn: ["verify-command"],
      input: { phase: "review" },
      timeoutMs: 30 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "resolve-delivery",
      type: "gitea.resolve_delivery",
      dependsOn: ["independent-review"],
      timeoutMs: 30_000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "delivery-approval",
      type: "approval.wait",
      dependsOn: ["resolve-delivery"],
      input: { reason: "Final delivery requires human approval" },
      timeoutMs: 60 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "required",
    },
    {
      id: "git-push",
      type: "git.push",
      dependsOn: ["delivery-approval"],
      timeoutMs: 60_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "git-create-pr",
      type: "git.create_pr",
      dependsOn: ["git-push"],
      input: { title: "Automated implementation for issue" },
      timeoutMs: 60_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
  );

  return {
    id: `gitea.issue-to-pr${strategy === "full_superpowers" ? "" : `.${strategy.replace("issue_", "")}`}`,
    revision: "1",
    maxConcurrency: 1,
    maxArtifactBytes: 10 * 1024 * 1024,
    steps,
  };
}

export function buildAutoWorkflowDefinition() {
  const steps: StepDefinition[] = [
    {
      id: "fetch-issue",
      type: "gitea.fetch_issue",
      timeoutMs: 30_000,
      retries: 2,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "claim-issue",
      type: "gitea.claim_issue",
      dependsOn: ["fetch-issue"],
      timeoutMs: 30_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "worktree-create",
      type: "worktree.create",
      dependsOn: ["claim-issue"],
      timeoutMs: 60_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "auto-design",
      type: "gitea.agent_execute",
      dependsOn: ["worktree-create"],
      input: { phase: "auto_design" },
      timeoutMs: 30 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "implement-agent",
      type: "gitea.agent_execute",
      dependsOn: ["auto-design"],
      input: { phase: "implement" },
      timeoutMs: 60 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "verify-command",
      type: "verify.command",
      dependsOn: ["implement-agent"],
      input: { verificationProfile: "unit-test" },
      timeoutMs: 15 * 60 * 1000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "independent-review",
      type: "gitea.agent_execute",
      dependsOn: ["verify-command"],
      input: { phase: "review" },
      timeoutMs: 30 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "resolve-delivery",
      type: "gitea.resolve_delivery",
      dependsOn: ["independent-review"],
      timeoutMs: 30_000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "git-push",
      type: "git.push",
      dependsOn: ["resolve-delivery"],
      timeoutMs: 60_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "git-create-pr",
      type: "git.create_pr",
      dependsOn: ["git-push"],
      input: { title: "Automated implementation for issue" },
      timeoutMs: 60_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
  ];

  return {
    id: "gitea.issue-to-pr.auto",
    revision: "1",
    maxConcurrency: 1,
    maxArtifactBytes: 10 * 1024 * 1024,
    steps,
  };
}

export function buildPlanWorkflowDefinition() {
  const steps: StepDefinition[] = [
    {
      id: "fetch-issue",
      type: "gitea.fetch_issue",
      timeoutMs: 30_000,
      retries: 2,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "claim-issue",
      type: "gitea.claim_issue",
      dependsOn: ["fetch-issue"],
      timeoutMs: 30_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "worktree-create",
      type: "worktree.create",
      dependsOn: ["claim-issue"],
      timeoutMs: 60_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "brainstorm-agent",
      type: "gitea.agent_execute",
      dependsOn: ["worktree-create"],
      input: { phase: "brainstorm" },
      timeoutMs: 30 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "gate-brainstorm",
      type: "approval.wait",
      dependsOn: ["brainstorm-agent"],
      input: { phase: "brainstorm", reason: "Brainstorm proposal requires confirmation" },
      timeoutMs: 60 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "required",
    },
    {
      id: "spec-agent",
      type: "gitea.agent_execute",
      dependsOn: ["gate-brainstorm"],
      input: { phase: "spec" },
      timeoutMs: 30 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "gate-spec",
      type: "approval.wait",
      dependsOn: ["spec-agent"],
      input: { phase: "spec", reason: "Design spec requires confirmation" },
      timeoutMs: 60 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "required",
    },
    {
      id: "plan-agent",
      type: "gitea.agent_execute",
      dependsOn: ["gate-spec"],
      input: { phase: "plan" },
      timeoutMs: 30 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "gate-plan",
      type: "approval.wait",
      dependsOn: ["plan-agent"],
      input: { phase: "plan", reason: "Implementation plan requires confirmation" },
      timeoutMs: 60 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "required",
    },
    {
      id: "implement-agent",
      type: "gitea.agent_execute",
      dependsOn: ["gate-plan"],
      input: { phase: "implement" },
      timeoutMs: 60 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "verify-command",
      type: "verify.command",
      dependsOn: ["implement-agent"],
      input: { verificationProfile: "unit-test" },
      timeoutMs: 15 * 60 * 1000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "independent-review",
      type: "gitea.agent_execute",
      dependsOn: ["verify-command"],
      input: { phase: "review" },
      timeoutMs: 30 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "resolve-delivery",
      type: "gitea.resolve_delivery",
      dependsOn: ["independent-review"],
      timeoutMs: 30_000,
      retries: 0,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "gate-delivery",
      type: "approval.wait",
      dependsOn: ["resolve-delivery"],
      input: { phase: "delivery", reason: "Final PR delivery requires confirmation" },
      timeoutMs: 60 * 60 * 1000,
      retries: 0,
      concurrency: 1,
      approval: "required",
    },
    {
      id: "git-push",
      type: "git.push",
      dependsOn: ["gate-delivery"],
      timeoutMs: 60_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
    {
      id: "git-create-pr",
      type: "git.create_pr",
      dependsOn: ["git-push"],
      input: { title: "Automated implementation for issue" },
      timeoutMs: 60_000,
      retries: 1,
      concurrency: 1,
      approval: "automatic",
    },
  ];

  return {
    id: "gitea.issue-to-pr.plan",
    revision: "1",
    maxConcurrency: 1,
    maxArtifactBytes: 10 * 1024 * 1024,
    steps,
  };
}

export const giteaWorkflowPresets: PluginWorkflowPreset[] = [
  {
    workflowId: "gitea.issue-to-pr",
    name: "Gitea Superpowers Pipeline (Full)",
    sourcePreset: "gitea-workflow",
    definition: buildGiteaWorkflowDefinition("full_superpowers"),
  },
  {
    workflowId: "gitea.issue-to-pr.auto",
    name: "Gitea Superpowers Pipeline (Auto)",
    sourcePreset: "gitea-workflow",
    definition: buildAutoWorkflowDefinition(),
  },
  {
    workflowId: "gitea.issue-to-pr.plan",
    name: "Gitea Superpowers Pipeline (Plan)",
    sourcePreset: "gitea-workflow",
    definition: buildPlanWorkflowDefinition(),
  },
  {
    workflowId: "gitea.issue-to-pr.preapproved",
    name: "Gitea Superpowers Pipeline (Preapproved)",
    sourcePreset: "gitea-workflow",
    definition: buildGiteaWorkflowDefinition("issue_preapproved"),
  },
  {
    workflowId: "gitea.issue-to-pr.unattended",
    name: "Gitea Superpowers Pipeline (Unattended)",
    sourcePreset: "gitea-workflow",
    definition: buildGiteaWorkflowDefinition("unattended"),
  },
];

export const issueToPrPreset: PluginWorkflowPreset = giteaWorkflowPresets[0]!;
